curl -o example_data/ChIP/ENCFF920ZZU.bed.gz -L https://www.encodeproject.org/files/ENCFF920ZZU/@@download/ENCFF920ZZU.bed.gz
curl -o example_data/ChIP/ENCFF639EBZ.bed.gz -L https://www.encodeproject.org/files/ENCFF639EBZ/@@download/ENCFF639EBZ.bed.gz
curl -o example_data/ChIP/ENCFF984YJS.bed.gz -L https://www.encodeproject.org/files/ENCFF984YJS/@@download/ENCFF984YJS.bed.gz
curl -o example_data/ChIP/ENCFF690LYQ.bed.gz -L https://www.encodeproject.org/files/ENCFF690LYQ/@@download/ENCFF690LYQ.bed.gz
curl -o example_data/ChIP/ENCFF126COV.bed.gz -L https://www.encodeproject.org/files/ENCFF126COV/@@download/ENCFF126COV.bed.gz
curl -o example_data/ChIP/ENCFF341GPU.bed.gz -L https://www.encodeproject.org/files/ENCFF341GPU/@@download/ENCFF341GPU.bed.gz
curl -o example_data/ChIP/ENCFF735INH.bed.gz -L https://www.encodeproject.org/files/ENCFF735INH/@@download/ENCFF735INH.bed.gz
curl -o example_data/ChIP/ENCFF707SCN.bed.gz -L https://www.encodeproject.org/files/ENCFF707SCN/@@download/ENCFF707SCN.bed.gz
curl -o example_data/ChIP/ENCFF279LCA.bed.gz -L https://www.encodeproject.org/files/ENCFF279LCA/@@download/ENCFF279LCA.bed.gz
curl -o example_data/ChIP/ENCFF920RXL.bed.gz -L https://www.encodeproject.org/files/ENCFF920RXL/@@download/ENCFF920RXL.bed.gz
curl -o example_data/ChIP/ENCFF039NJX.bed.gz -L https://www.encodeproject.org/files/ENCFF039NJX/@@download/ENCFF039NJX.bed.gz
curl -o example_data/ChIP/ENCFF941OPK.bed.gz -L https://www.encodeproject.org/files/ENCFF941OPK/@@download/ENCFF941OPK.bed.gz
curl -o example_data/ChIP/ENCFF074NWW.bed.gz -L https://www.encodeproject.org/files/ENCFF074NWW/@@download/ENCFF074NWW.bed.gz
curl -o example_data/ChIP/ENCFF073WXU.bed.gz -L https://www.encodeproject.org/files/ENCFF073WXU/@@download/ENCFF073WXU.bed.gz
curl -o example_data/ChIP/ENCFF735IWA.bed.gz -L https://www.encodeproject.org/files/ENCFF735IWA/@@download/ENCFF735IWA.bed.gz
curl -o example_data/ChIP/ENCFF627TXO.bed.gz -L https://www.encodeproject.org/files/ENCFF627TXO/@@download/ENCFF627TXO.bed.gz
curl -o example_data/ChIP/ENCFF919WHQ.bed.gz -L https://www.encodeproject.org/files/ENCFF919WHQ/@@download/ENCFF919WHQ.bed.gz
curl -o example_data/ChIP/ENCFF665ITW.bed.gz -L https://www.encodeproject.org/files/ENCFF665ITW/@@download/ENCFF665ITW.bed.gz
curl -o example_data/ChIP/ENCFF867MXB.bed.gz -L https://www.encodeproject.org/files/ENCFF867MXB/@@download/ENCFF867MXB.bed.gz
curl -o example_data/ChIP/ENCFF430ZZC.bed.gz -L https://www.encodeproject.org/files/ENCFF430ZZC/@@download/ENCFF430ZZC.bed.gz
curl -o example_data/ChIP/ENCFF102AJD.bed.gz -L https://www.encodeproject.org/files/ENCFF102AJD/@@download/ENCFF102AJD.bed.gz
curl -o example_data/ChIP/ENCFF506HQQ.bed.gz -L https://www.encodeproject.org/files/ENCFF506HQQ/@@download/ENCFF506HQQ.bed.gz
curl -o example_data/ChIP/ENCFF934NUU.bed.gz -L https://www.encodeproject.org/files/ENCFF934NUU/@@download/ENCFF934NUU.bed.gz
curl -o example_data/ChIP/ENCFF156GBL.bed.gz -L https://www.encodeproject.org/files/ENCFF156GBL/@@download/ENCFF156GBL.bed.gz
curl -o example_data/ChIP/ENCFF036WSP.bed.gz -L https://www.encodeproject.org/files/ENCFF036WSP/@@download/ENCFF036WSP.bed.gz
curl -o example_data/ChIP/ENCFF621JDK.bed.gz -L https://www.encodeproject.org/files/ENCFF621JDK/@@download/ENCFF621JDK.bed.gz
curl -o example_data/ChIP/ENCFF295ECE.bed.gz -L https://www.encodeproject.org/files/ENCFF295ECE/@@download/ENCFF295ECE.bed.gz
curl -o example_data/ChIP/ENCFF144TVZ.bed.gz -L https://www.encodeproject.org/files/ENCFF144TVZ/@@download/ENCFF144TVZ.bed.gz
curl -o example_data/ChIP/ENCFF154NON.bed.gz -L https://www.encodeproject.org/files/ENCFF154NON/@@download/ENCFF154NON.bed.gz
curl -o example_data/ChIP/ENCFF011ZFF.bed.gz -L https://www.encodeproject.org/files/ENCFF011ZFF/@@download/ENCFF011ZFF.bed.gz
curl -o example_data/ChIP/ENCFF266DFC.bed.gz -L https://www.encodeproject.org/files/ENCFF266DFC/@@download/ENCFF266DFC.bed.gz
curl -o example_data/ChIP/ENCFF291ITU.bed.gz -L https://www.encodeproject.org/files/ENCFF291ITU/@@download/ENCFF291ITU.bed.gz
curl -o example_data/ChIP/ENCFF267BPJ.bed.gz -L https://www.encodeproject.org/files/ENCFF267BPJ/@@download/ENCFF267BPJ.bed.gz
curl -o example_data/ChIP/ENCFF601ABX.bed.gz -L https://www.encodeproject.org/files/ENCFF601ABX/@@download/ENCFF601ABX.bed.gz
curl -o example_data/ChIP/ENCFF185GRE.bed.gz -L https://www.encodeproject.org/files/ENCFF185GRE/@@download/ENCFF185GRE.bed.gz
curl -o example_data/ChIP/ENCFF363ZZQ.bed.gz -L https://www.encodeproject.org/files/ENCFF363ZZQ/@@download/ENCFF363ZZQ.bed.gz
curl -o example_data/ChIP/ENCFF166RHN.bed.gz -L https://www.encodeproject.org/files/ENCFF166RHN/@@download/ENCFF166RHN.bed.gz
curl -o example_data/ChIP/ENCFF466GRZ.bed.gz -L https://www.encodeproject.org/files/ENCFF466GRZ/@@download/ENCFF466GRZ.bed.gz
curl -o example_data/ChIP/ENCFF488JBJ.bed.gz -L https://www.encodeproject.org/files/ENCFF488JBJ/@@download/ENCFF488JBJ.bed.gz
curl -o example_data/ChIP/ENCFF572HME.bed.gz -L https://www.encodeproject.org/files/ENCFF572HME/@@download/ENCFF572HME.bed.gz
curl -o example_data/ChIP/ENCFF109DAX.bed.gz -L https://www.encodeproject.org/files/ENCFF109DAX/@@download/ENCFF109DAX.bed.gz
curl -o example_data/ChIP/ENCFF681NAI.bed.gz -L https://www.encodeproject.org/files/ENCFF681NAI/@@download/ENCFF681NAI.bed.gz
curl -o example_data/ChIP/ENCFF179OVA.bed.gz -L https://www.encodeproject.org/files/ENCFF179OVA/@@download/ENCFF179OVA.bed.gz
curl -o example_data/ChIP/ENCFF783HST.bed.gz -L https://www.encodeproject.org/files/ENCFF783HST/@@download/ENCFF783HST.bed.gz
curl -o example_data/ChIP/ENCFF058MHE.bed.gz -L https://www.encodeproject.org/files/ENCFF058MHE/@@download/ENCFF058MHE.bed.gz
curl -o example_data/ChIP/ENCFF051RKM.bed.gz -L https://www.encodeproject.org/files/ENCFF051RKM/@@download/ENCFF051RKM.bed.gz
curl -o example_data/ChIP/ENCFF263LLY.bed.gz -L https://www.encodeproject.org/files/ENCFF263LLY/@@download/ENCFF263LLY.bed.gz
curl -o example_data/ChIP/ENCFF668WHA.bed.gz -L https://www.encodeproject.org/files/ENCFF668WHA/@@download/ENCFF668WHA.bed.gz
curl -o example_data/ChIP/ENCFF213LUC.bed.gz -L https://www.encodeproject.org/files/ENCFF213LUC/@@download/ENCFF213LUC.bed.gz
curl -o example_data/ChIP/ENCFF575JGX.bed.gz -L https://www.encodeproject.org/files/ENCFF575JGX/@@download/ENCFF575JGX.bed.gz
curl -o example_data/ChIP/ENCFF236ZXL.bed.gz -L https://www.encodeproject.org/files/ENCFF236ZXL/@@download/ENCFF236ZXL.bed.gz
curl -o example_data/ChIP/ENCFF190WOL.bed.gz -L https://www.encodeproject.org/files/ENCFF190WOL/@@download/ENCFF190WOL.bed.gz
curl -o example_data/ChIP/ENCFF718YZD.bed.gz -L https://www.encodeproject.org/files/ENCFF718YZD/@@download/ENCFF718YZD.bed.gz
curl -o example_data/ChIP/ENCFF147YIC.bed.gz -L https://www.encodeproject.org/files/ENCFF147YIC/@@download/ENCFF147YIC.bed.gz
curl -o example_data/ChIP/ENCFF194SDY.bed.gz -L https://www.encodeproject.org/files/ENCFF194SDY/@@download/ENCFF194SDY.bed.gz
curl -o example_data/ChIP/ENCFF297PNE.bed.gz -L https://www.encodeproject.org/files/ENCFF297PNE/@@download/ENCFF297PNE.bed.gz
curl -o example_data/ChIP/ENCFF949GGM.bed.gz -L https://www.encodeproject.org/files/ENCFF949GGM/@@download/ENCFF949GGM.bed.gz
curl -o example_data/ChIP/ENCFF924WZW.bed.gz -L https://www.encodeproject.org/files/ENCFF924WZW/@@download/ENCFF924WZW.bed.gz
curl -o example_data/ChIP/ENCFF932ESA.bed.gz -L https://www.encodeproject.org/files/ENCFF932ESA/@@download/ENCFF932ESA.bed.gz
curl -o example_data/ChIP/ENCFF782AVC.bed.gz -L https://www.encodeproject.org/files/ENCFF782AVC/@@download/ENCFF782AVC.bed.gz
curl -o example_data/ChIP/ENCFF796WLI.bed.gz -L https://www.encodeproject.org/files/ENCFF796WLI/@@download/ENCFF796WLI.bed.gz
curl -o example_data/ChIP/ENCFF700EMX.bed.gz -L https://www.encodeproject.org/files/ENCFF700EMX/@@download/ENCFF700EMX.bed.gz
curl -o example_data/ChIP/ENCFF602DII.bed.gz -L https://www.encodeproject.org/files/ENCFF602DII/@@download/ENCFF602DII.bed.gz
curl -o example_data/ChIP/ENCFF398LRM.bed.gz -L https://www.encodeproject.org/files/ENCFF398LRM/@@download/ENCFF398LRM.bed.gz
curl -o example_data/ChIP/ENCFF661TBC.bed.gz -L https://www.encodeproject.org/files/ENCFF661TBC/@@download/ENCFF661TBC.bed.gz
curl -o example_data/ChIP/ENCFF087YMD.bed.gz -L https://www.encodeproject.org/files/ENCFF087YMD/@@download/ENCFF087YMD.bed.gz
curl -o example_data/ChIP/ENCFF653XNX.bed.gz -L https://www.encodeproject.org/files/ENCFF653XNX/@@download/ENCFF653XNX.bed.gz
curl -o example_data/ChIP/ENCFF352QAJ.bed.gz -L https://www.encodeproject.org/files/ENCFF352QAJ/@@download/ENCFF352QAJ.bed.gz
curl -o example_data/ChIP/ENCFF480LXX.bed.gz -L https://www.encodeproject.org/files/ENCFF480LXX/@@download/ENCFF480LXX.bed.gz
curl -o example_data/ChIP/ENCFF398HVZ.bed.gz -L https://www.encodeproject.org/files/ENCFF398HVZ/@@download/ENCFF398HVZ.bed.gz
curl -o example_data/ChIP/ENCFF087YEA.bed.gz -L https://www.encodeproject.org/files/ENCFF087YEA/@@download/ENCFF087YEA.bed.gz
curl -o example_data/ChIP/ENCFF750DHO.bed.gz -L https://www.encodeproject.org/files/ENCFF750DHO/@@download/ENCFF750DHO.bed.gz
curl -o example_data/ChIP/ENCFF016AVO.bed.gz -L https://www.encodeproject.org/files/ENCFF016AVO/@@download/ENCFF016AVO.bed.gz
curl -o example_data/ChIP/ENCFF044NDZ.bed.gz -L https://www.encodeproject.org/files/ENCFF044NDZ/@@download/ENCFF044NDZ.bed.gz
curl -o example_data/ChIP/ENCFF745XNP.bed.gz -L https://www.encodeproject.org/files/ENCFF745XNP/@@download/ENCFF745XNP.bed.gz
curl -o example_data/ChIP/ENCFF110TIS.bed.gz -L https://www.encodeproject.org/files/ENCFF110TIS/@@download/ENCFF110TIS.bed.gz
curl -o example_data/ChIP/ENCFF412ERQ.bed.gz -L https://www.encodeproject.org/files/ENCFF412ERQ/@@download/ENCFF412ERQ.bed.gz
curl -o example_data/ChIP/ENCFF992FNM.bed.gz -L https://www.encodeproject.org/files/ENCFF992FNM/@@download/ENCFF992FNM.bed.gz
curl -o example_data/ChIP/ENCFF008SFA.bed.gz -L https://www.encodeproject.org/files/ENCFF008SFA/@@download/ENCFF008SFA.bed.gz
curl -o example_data/ChIP/ENCFF164WWT.bed.gz -L https://www.encodeproject.org/files/ENCFF164WWT/@@download/ENCFF164WWT.bed.gz
curl -o example_data/ChIP/ENCFF902XUL.bed.gz -L https://www.encodeproject.org/files/ENCFF902XUL/@@download/ENCFF902XUL.bed.gz
curl -o example_data/ChIP/ENCFF427ZVV.bed.gz -L https://www.encodeproject.org/files/ENCFF427ZVV/@@download/ENCFF427ZVV.bed.gz
curl -o example_data/ChIP/ENCFF477OLK.bed.gz -L https://www.encodeproject.org/files/ENCFF477OLK/@@download/ENCFF477OLK.bed.gz
curl -o example_data/ChIP/ENCFF499KPW.bed.gz -L https://www.encodeproject.org/files/ENCFF499KPW/@@download/ENCFF499KPW.bed.gz
curl -o example_data/ChIP/ENCFF743ABH.bed.gz -L https://www.encodeproject.org/files/ENCFF743ABH/@@download/ENCFF743ABH.bed.gz
curl -o example_data/ChIP/ENCFF148ZVZ.bed.gz -L https://www.encodeproject.org/files/ENCFF148ZVZ/@@download/ENCFF148ZVZ.bed.gz
curl -o example_data/ChIP/ENCFF367EQO.bed.gz -L https://www.encodeproject.org/files/ENCFF367EQO/@@download/ENCFF367EQO.bed.gz
curl -o example_data/ChIP/ENCFF101LXN.bed.gz -L https://www.encodeproject.org/files/ENCFF101LXN/@@download/ENCFF101LXN.bed.gz
curl -o example_data/ChIP/ENCFF527SAZ.bed.gz -L https://www.encodeproject.org/files/ENCFF527SAZ/@@download/ENCFF527SAZ.bed.gz
curl -o example_data/ChIP/ENCFF322BYQ.bed.gz -L https://www.encodeproject.org/files/ENCFF322BYQ/@@download/ENCFF322BYQ.bed.gz
curl -o example_data/ChIP/ENCFF371LSA.bed.gz -L https://www.encodeproject.org/files/ENCFF371LSA/@@download/ENCFF371LSA.bed.gz
curl -o example_data/ChIP/ENCFF798IOJ.bed.gz -L https://www.encodeproject.org/files/ENCFF798IOJ/@@download/ENCFF798IOJ.bed.gz
curl -o example_data/ChIP/ENCFF829QJB.bed.gz -L https://www.encodeproject.org/files/ENCFF829QJB/@@download/ENCFF829QJB.bed.gz
curl -o example_data/ChIP/ENCFF148DCA.bed.gz -L https://www.encodeproject.org/files/ENCFF148DCA/@@download/ENCFF148DCA.bed.gz
curl -o example_data/ChIP/ENCFF789WVF.bed.gz -L https://www.encodeproject.org/files/ENCFF789WVF/@@download/ENCFF789WVF.bed.gz
curl -o example_data/ChIP/ENCFF747NGN.bed.gz -L https://www.encodeproject.org/files/ENCFF747NGN/@@download/ENCFF747NGN.bed.gz
curl -o example_data/ChIP/ENCFF830RFY.bed.gz -L https://www.encodeproject.org/files/ENCFF830RFY/@@download/ENCFF830RFY.bed.gz
curl -o example_data/ChIP/ENCFF622FZA.bed.gz -L https://www.encodeproject.org/files/ENCFF622FZA/@@download/ENCFF622FZA.bed.gz
curl -o example_data/ChIP/ENCFF222FPY.bed.gz -L https://www.encodeproject.org/files/ENCFF222FPY/@@download/ENCFF222FPY.bed.gz
curl -o example_data/ChIP/ENCFF684MQZ.bed.gz -L https://www.encodeproject.org/files/ENCFF684MQZ/@@download/ENCFF684MQZ.bed.gz
curl -o example_data/ChIP/ENCFF880ZSE.bed.gz -L https://www.encodeproject.org/files/ENCFF880ZSE/@@download/ENCFF880ZSE.bed.gz
curl -o example_data/ChIP/ENCFF848BAO.bed.gz -L https://www.encodeproject.org/files/ENCFF848BAO/@@download/ENCFF848BAO.bed.gz
curl -o example_data/ChIP/ENCFF386VVR.bed.gz -L https://www.encodeproject.org/files/ENCFF386VVR/@@download/ENCFF386VVR.bed.gz
curl -o example_data/ChIP/ENCFF658JCK.bed.gz -L https://www.encodeproject.org/files/ENCFF658JCK/@@download/ENCFF658JCK.bed.gz
curl -o example_data/ChIP/ENCFF757XFT.bed.gz -L https://www.encodeproject.org/files/ENCFF757XFT/@@download/ENCFF757XFT.bed.gz
curl -o example_data/ChIP/ENCFF695NUV.bed.gz -L https://www.encodeproject.org/files/ENCFF695NUV/@@download/ENCFF695NUV.bed.gz
curl -o example_data/ChIP/ENCFF845PRO.bed.gz -L https://www.encodeproject.org/files/ENCFF845PRO/@@download/ENCFF845PRO.bed.gz
curl -o example_data/ChIP/ENCFF631OFN.bed.gz -L https://www.encodeproject.org/files/ENCFF631OFN/@@download/ENCFF631OFN.bed.gz
curl -o example_data/ChIP/ENCFF161YKX.bed.gz -L https://www.encodeproject.org/files/ENCFF161YKX/@@download/ENCFF161YKX.bed.gz
curl -o example_data/ChIP/ENCFF015BOI.bed.gz -L https://www.encodeproject.org/files/ENCFF015BOI/@@download/ENCFF015BOI.bed.gz
curl -o example_data/ChIP/ENCFF159BPU.bed.gz -L https://www.encodeproject.org/files/ENCFF159BPU/@@download/ENCFF159BPU.bed.gz
curl -o example_data/ChIP/ENCFF568JAR.bed.gz -L https://www.encodeproject.org/files/ENCFF568JAR/@@download/ENCFF568JAR.bed.gz
curl -o example_data/ChIP/ENCFF305KHK.bed.gz -L https://www.encodeproject.org/files/ENCFF305KHK/@@download/ENCFF305KHK.bed.gz
curl -o example_data/ChIP/ENCFF560ZBF.bed.gz -L https://www.encodeproject.org/files/ENCFF560ZBF/@@download/ENCFF560ZBF.bed.gz
curl -o example_data/ChIP/ENCFF115IAV.bed.gz -L https://www.encodeproject.org/files/ENCFF115IAV/@@download/ENCFF115IAV.bed.gz
curl -o example_data/ChIP/ENCFF548SKE.bed.gz -L https://www.encodeproject.org/files/ENCFF548SKE/@@download/ENCFF548SKE.bed.gz
curl -o example_data/ChIP/ENCFF319IUM.bed.gz -L https://www.encodeproject.org/files/ENCFF319IUM/@@download/ENCFF319IUM.bed.gz
curl -o example_data/ChIP/ENCFF740MEO.bed.gz -L https://www.encodeproject.org/files/ENCFF740MEO/@@download/ENCFF740MEO.bed.gz
curl -o example_data/ChIP/ENCFF892ONF.bed.gz -L https://www.encodeproject.org/files/ENCFF892ONF/@@download/ENCFF892ONF.bed.gz
curl -o example_data/ChIP/ENCFF423XAX.bed.gz -L https://www.encodeproject.org/files/ENCFF423XAX/@@download/ENCFF423XAX.bed.gz
curl -o example_data/ChIP/ENCFF266CND.bed.gz -L https://www.encodeproject.org/files/ENCFF266CND/@@download/ENCFF266CND.bed.gz
curl -o example_data/ChIP/ENCFF461HQA.bed.gz -L https://www.encodeproject.org/files/ENCFF461HQA/@@download/ENCFF461HQA.bed.gz
curl -o example_data/ChIP/ENCFF921NGG.bed.gz -L https://www.encodeproject.org/files/ENCFF921NGG/@@download/ENCFF921NGG.bed.gz
curl -o example_data/ChIP/ENCFF412VYJ.bed.gz -L https://www.encodeproject.org/files/ENCFF412VYJ/@@download/ENCFF412VYJ.bed.gz
curl -o example_data/ChIP/ENCFF069DQE.bed.gz -L https://www.encodeproject.org/files/ENCFF069DQE/@@download/ENCFF069DQE.bed.gz
curl -o example_data/ChIP/ENCFF217GOU.bed.gz -L https://www.encodeproject.org/files/ENCFF217GOU/@@download/ENCFF217GOU.bed.gz
curl -o example_data/ChIP/ENCFF145QEJ.bed.gz -L https://www.encodeproject.org/files/ENCFF145QEJ/@@download/ENCFF145QEJ.bed.gz
curl -o example_data/ChIP/ENCFF161YYL.bed.gz -L https://www.encodeproject.org/files/ENCFF161YYL/@@download/ENCFF161YYL.bed.gz
curl -o example_data/ChIP/ENCFF101MSP.bed.gz -L https://www.encodeproject.org/files/ENCFF101MSP/@@download/ENCFF101MSP.bed.gz
curl -o example_data/ChIP/ENCFF277KTG.bed.gz -L https://www.encodeproject.org/files/ENCFF277KTG/@@download/ENCFF277KTG.bed.gz
curl -o example_data/ChIP/ENCFF651RRS.bed.gz -L https://www.encodeproject.org/files/ENCFF651RRS/@@download/ENCFF651RRS.bed.gz
curl -o example_data/ChIP/ENCFF055BXR.bed.gz -L https://www.encodeproject.org/files/ENCFF055BXR/@@download/ENCFF055BXR.bed.gz
curl -o example_data/ChIP/ENCFF885RDD.bed.gz -L https://www.encodeproject.org/files/ENCFF885RDD/@@download/ENCFF885RDD.bed.gz
curl -o example_data/ChIP/ENCFF092HTT.bed.gz -L https://www.encodeproject.org/files/ENCFF092HTT/@@download/ENCFF092HTT.bed.gz
curl -o example_data/ChIP/ENCFF017WWU.bed.gz -L https://www.encodeproject.org/files/ENCFF017WWU/@@download/ENCFF017WWU.bed.gz
curl -o example_data/ChIP/ENCFF700NXM.bed.gz -L https://www.encodeproject.org/files/ENCFF700NXM/@@download/ENCFF700NXM.bed.gz
curl -o example_data/ChIP/ENCFF678MAP.bed.gz -L https://www.encodeproject.org/files/ENCFF678MAP/@@download/ENCFF678MAP.bed.gz
curl -o example_data/ChIP/ENCFF508PWL.bed.gz -L https://www.encodeproject.org/files/ENCFF508PWL/@@download/ENCFF508PWL.bed.gz
curl -o example_data/ChIP/ENCFF121BWC.bed.gz -L https://www.encodeproject.org/files/ENCFF121BWC/@@download/ENCFF121BWC.bed.gz
curl -o example_data/ChIP/ENCFF539PBL.bed.gz -L https://www.encodeproject.org/files/ENCFF539PBL/@@download/ENCFF539PBL.bed.gz
curl -o example_data/ChIP/ENCFF823ZLI.bed.gz -L https://www.encodeproject.org/files/ENCFF823ZLI/@@download/ENCFF823ZLI.bed.gz
curl -o example_data/ChIP/ENCFF827AXW.bed.gz -L https://www.encodeproject.org/files/ENCFF827AXW/@@download/ENCFF827AXW.bed.gz
curl -o example_data/ChIP/ENCFF250YXS.bed.gz -L https://www.encodeproject.org/files/ENCFF250YXS/@@download/ENCFF250YXS.bed.gz
curl -o example_data/ChIP/ENCFF575EGM.bed.gz -L https://www.encodeproject.org/files/ENCFF575EGM/@@download/ENCFF575EGM.bed.gz
curl -o example_data/ChIP/ENCFF838MFW.bed.gz -L https://www.encodeproject.org/files/ENCFF838MFW/@@download/ENCFF838MFW.bed.gz
curl -o example_data/ChIP/ENCFF799UIH.bed.gz -L https://www.encodeproject.org/files/ENCFF799UIH/@@download/ENCFF799UIH.bed.gz
curl -o example_data/ChIP/ENCFF274ZTV.bed.gz -L https://www.encodeproject.org/files/ENCFF274ZTV/@@download/ENCFF274ZTV.bed.gz
curl -o example_data/ChIP/ENCFF548KCT.bed.gz -L https://www.encodeproject.org/files/ENCFF548KCT/@@download/ENCFF548KCT.bed.gz
curl -o example_data/ChIP/ENCFF518OMQ.bed.gz -L https://www.encodeproject.org/files/ENCFF518OMQ/@@download/ENCFF518OMQ.bed.gz
curl -o example_data/ChIP/ENCFF515WFN.bed.gz -L https://www.encodeproject.org/files/ENCFF515WFN/@@download/ENCFF515WFN.bed.gz
curl -o example_data/ChIP/ENCFF512ALY.bed.gz -L https://www.encodeproject.org/files/ENCFF512ALY/@@download/ENCFF512ALY.bed.gz
curl -o example_data/ChIP/ENCFF912TQD.bed.gz -L https://www.encodeproject.org/files/ENCFF912TQD/@@download/ENCFF912TQD.bed.gz
curl -o example_data/ChIP/ENCFF932JUB.bed.gz -L https://www.encodeproject.org/files/ENCFF932JUB/@@download/ENCFF932JUB.bed.gz
curl -o example_data/ChIP/ENCFF825MJJ.bed.gz -L https://www.encodeproject.org/files/ENCFF825MJJ/@@download/ENCFF825MJJ.bed.gz
curl -o example_data/ChIP/ENCFF212MTQ.bed.gz -L https://www.encodeproject.org/files/ENCFF212MTQ/@@download/ENCFF212MTQ.bed.gz
curl -o example_data/ChIP/ENCFF193JYL.bed.gz -L https://www.encodeproject.org/files/ENCFF193JYL/@@download/ENCFF193JYL.bed.gz
curl -o example_data/ChIP/ENCFF565UBS.bed.gz -L https://www.encodeproject.org/files/ENCFF565UBS/@@download/ENCFF565UBS.bed.gz
curl -o example_data/ChIP/ENCFF346DAK.bed.gz -L https://www.encodeproject.org/files/ENCFF346DAK/@@download/ENCFF346DAK.bed.gz
curl -o example_data/ChIP/ENCFF651AYT.bed.gz -L https://www.encodeproject.org/files/ENCFF651AYT/@@download/ENCFF651AYT.bed.gz
curl -o example_data/ChIP/ENCFF242NCQ.bed.gz -L https://www.encodeproject.org/files/ENCFF242NCQ/@@download/ENCFF242NCQ.bed.gz
curl -o example_data/ChIP/ENCFF643GNF.bed.gz -L https://www.encodeproject.org/files/ENCFF643GNF/@@download/ENCFF643GNF.bed.gz
curl -o example_data/ChIP/ENCFF832SKZ.bed.gz -L https://www.encodeproject.org/files/ENCFF832SKZ/@@download/ENCFF832SKZ.bed.gz
curl -o example_data/ChIP/ENCFF910NPG.bed.gz -L https://www.encodeproject.org/files/ENCFF910NPG/@@download/ENCFF910NPG.bed.gz
curl -o example_data/ChIP/ENCFF916ZJW.bed.gz -L https://www.encodeproject.org/files/ENCFF916ZJW/@@download/ENCFF916ZJW.bed.gz
curl -o example_data/ChIP/ENCFF664CDO.bed.gz -L https://www.encodeproject.org/files/ENCFF664CDO/@@download/ENCFF664CDO.bed.gz
curl -o example_data/ChIP/ENCFF688PWU.bed.gz -L https://www.encodeproject.org/files/ENCFF688PWU/@@download/ENCFF688PWU.bed.gz
curl -o example_data/ChIP/ENCFF060YZU.bed.gz -L https://www.encodeproject.org/files/ENCFF060YZU/@@download/ENCFF060YZU.bed.gz
curl -o example_data/ChIP/ENCFF042RUT.bed.gz -L https://www.encodeproject.org/files/ENCFF042RUT/@@download/ENCFF042RUT.bed.gz
curl -o example_data/ChIP/ENCFF913ZLS.bed.gz -L https://www.encodeproject.org/files/ENCFF913ZLS/@@download/ENCFF913ZLS.bed.gz
curl -o example_data/ChIP/ENCFF831EUF.bed.gz -L https://www.encodeproject.org/files/ENCFF831EUF/@@download/ENCFF831EUF.bed.gz
curl -o example_data/ChIP/ENCFF854XZI.bed.gz -L https://www.encodeproject.org/files/ENCFF854XZI/@@download/ENCFF854XZI.bed.gz
curl -o example_data/ChIP/ENCFF569QEB.bed.gz -L https://www.encodeproject.org/files/ENCFF569QEB/@@download/ENCFF569QEB.bed.gz
curl -o example_data/ChIP/ENCFF127TLY.bed.gz -L https://www.encodeproject.org/files/ENCFF127TLY/@@download/ENCFF127TLY.bed.gz
curl -o example_data/ChIP/ENCFF899IHR.bed.gz -L https://www.encodeproject.org/files/ENCFF899IHR/@@download/ENCFF899IHR.bed.gz
curl -o example_data/ChIP/ENCFF405RLC.bed.gz -L https://www.encodeproject.org/files/ENCFF405RLC/@@download/ENCFF405RLC.bed.gz
curl -o example_data/ChIP/ENCFF090JJN.bed.gz -L https://www.encodeproject.org/files/ENCFF090JJN/@@download/ENCFF090JJN.bed.gz
curl -o example_data/ChIP/ENCFF543EOX.bed.gz -L https://www.encodeproject.org/files/ENCFF543EOX/@@download/ENCFF543EOX.bed.gz
curl -o example_data/ChIP/ENCFF076SSJ.bed.gz -L https://www.encodeproject.org/files/ENCFF076SSJ/@@download/ENCFF076SSJ.bed.gz
curl -o example_data/ChIP/ENCFF788IJB.bed.gz -L https://www.encodeproject.org/files/ENCFF788IJB/@@download/ENCFF788IJB.bed.gz
curl -o example_data/ChIP/ENCFF812AMG.bed.gz -L https://www.encodeproject.org/files/ENCFF812AMG/@@download/ENCFF812AMG.bed.gz
curl -o example_data/ChIP/ENCFF016EDE.bed.gz -L https://www.encodeproject.org/files/ENCFF016EDE/@@download/ENCFF016EDE.bed.gz
curl -o example_data/ChIP/ENCFF861KLL.bed.gz -L https://www.encodeproject.org/files/ENCFF861KLL/@@download/ENCFF861KLL.bed.gz
curl -o example_data/ChIP/ENCFF794HRO.bed.gz -L https://www.encodeproject.org/files/ENCFF794HRO/@@download/ENCFF794HRO.bed.gz
curl -o example_data/ChIP/ENCFF873MSF.bed.gz -L https://www.encodeproject.org/files/ENCFF873MSF/@@download/ENCFF873MSF.bed.gz
curl -o example_data/ChIP/ENCFF206SYO.bed.gz -L https://www.encodeproject.org/files/ENCFF206SYO/@@download/ENCFF206SYO.bed.gz
curl -o example_data/ChIP/ENCFF953BJP.bed.gz -L https://www.encodeproject.org/files/ENCFF953BJP/@@download/ENCFF953BJP.bed.gz
curl -o example_data/ChIP/ENCFF256ZXB.bed.gz -L https://www.encodeproject.org/files/ENCFF256ZXB/@@download/ENCFF256ZXB.bed.gz
curl -o example_data/ChIP/ENCFF188PRM.bed.gz -L https://www.encodeproject.org/files/ENCFF188PRM/@@download/ENCFF188PRM.bed.gz
curl -o example_data/ChIP/ENCFF934VQE.bed.gz -L https://www.encodeproject.org/files/ENCFF934VQE/@@download/ENCFF934VQE.bed.gz
curl -o example_data/ChIP/ENCFF111IYL.bed.gz -L https://www.encodeproject.org/files/ENCFF111IYL/@@download/ENCFF111IYL.bed.gz
curl -o example_data/ChIP/ENCFF898EQO.bed.gz -L https://www.encodeproject.org/files/ENCFF898EQO/@@download/ENCFF898EQO.bed.gz
curl -o example_data/ChIP/ENCFF144OZH.bed.gz -L https://www.encodeproject.org/files/ENCFF144OZH/@@download/ENCFF144OZH.bed.gz
curl -o example_data/ChIP/ENCFF370NSR.bed.gz -L https://www.encodeproject.org/files/ENCFF370NSR/@@download/ENCFF370NSR.bed.gz
curl -o example_data/ChIP/ENCFF846DBY.bed.gz -L https://www.encodeproject.org/files/ENCFF846DBY/@@download/ENCFF846DBY.bed.gz
curl -o example_data/ChIP/ENCFF128YSX.bed.gz -L https://www.encodeproject.org/files/ENCFF128YSX/@@download/ENCFF128YSX.bed.gz
curl -o example_data/ChIP/ENCFF937RLN.bed.gz -L https://www.encodeproject.org/files/ENCFF937RLN/@@download/ENCFF937RLN.bed.gz
curl -o example_data/ChIP/ENCFF916IVW.bed.gz -L https://www.encodeproject.org/files/ENCFF916IVW/@@download/ENCFF916IVW.bed.gz
curl -o example_data/ChIP/ENCFF108OTF.bed.gz -L https://www.encodeproject.org/files/ENCFF108OTF/@@download/ENCFF108OTF.bed.gz
curl -o example_data/ChIP/ENCFF927MTH.bed.gz -L https://www.encodeproject.org/files/ENCFF927MTH/@@download/ENCFF927MTH.bed.gz
curl -o example_data/ChIP/ENCFF176EQP.bed.gz -L https://www.encodeproject.org/files/ENCFF176EQP/@@download/ENCFF176EQP.bed.gz
curl -o example_data/ChIP/ENCFF327QOB.bed.gz -L https://www.encodeproject.org/files/ENCFF327QOB/@@download/ENCFF327QOB.bed.gz
curl -o example_data/ChIP/ENCFF935MTW.bed.gz -L https://www.encodeproject.org/files/ENCFF935MTW/@@download/ENCFF935MTW.bed.gz
curl -o example_data/ChIP/ENCFF008MOP.bed.gz -L https://www.encodeproject.org/files/ENCFF008MOP/@@download/ENCFF008MOP.bed.gz
curl -o example_data/ChIP/ENCFF073ETO.bed.gz -L https://www.encodeproject.org/files/ENCFF073ETO/@@download/ENCFF073ETO.bed.gz
curl -o example_data/ChIP/ENCFF641FRQ.bed.gz -L https://www.encodeproject.org/files/ENCFF641FRQ/@@download/ENCFF641FRQ.bed.gz
curl -o example_data/ChIP/ENCFF200EWT.bed.gz -L https://www.encodeproject.org/files/ENCFF200EWT/@@download/ENCFF200EWT.bed.gz
curl -o example_data/ChIP/ENCFF180LHH.bed.gz -L https://www.encodeproject.org/files/ENCFF180LHH/@@download/ENCFF180LHH.bed.gz
curl -o example_data/ChIP/ENCFF803IKO.bed.gz -L https://www.encodeproject.org/files/ENCFF803IKO/@@download/ENCFF803IKO.bed.gz
curl -o example_data/ChIP/ENCFF638OVH.bed.gz -L https://www.encodeproject.org/files/ENCFF638OVH/@@download/ENCFF638OVH.bed.gz
curl -o example_data/ChIP/ENCFF267MOT.bed.gz -L https://www.encodeproject.org/files/ENCFF267MOT/@@download/ENCFF267MOT.bed.gz
curl -o example_data/ChIP/ENCFF453JHO.bed.gz -L https://www.encodeproject.org/files/ENCFF453JHO/@@download/ENCFF453JHO.bed.gz
curl -o example_data/ChIP/ENCFF446SME.bed.gz -L https://www.encodeproject.org/files/ENCFF446SME/@@download/ENCFF446SME.bed.gz
curl -o example_data/ChIP/ENCFF323PJT.bed.gz -L https://www.encodeproject.org/files/ENCFF323PJT/@@download/ENCFF323PJT.bed.gz
curl -o example_data/ChIP/ENCFF794VOX.bed.gz -L https://www.encodeproject.org/files/ENCFF794VOX/@@download/ENCFF794VOX.bed.gz
curl -o example_data/ChIP/ENCFF045ELU.bed.gz -L https://www.encodeproject.org/files/ENCFF045ELU/@@download/ENCFF045ELU.bed.gz
curl -o example_data/ChIP/ENCFF275OIZ.bed.gz -L https://www.encodeproject.org/files/ENCFF275OIZ/@@download/ENCFF275OIZ.bed.gz
curl -o example_data/ChIP/ENCFF271JUU.bed.gz -L https://www.encodeproject.org/files/ENCFF271JUU/@@download/ENCFF271JUU.bed.gz
curl -o example_data/ChIP/ENCFF100EUY.bed.gz -L https://www.encodeproject.org/files/ENCFF100EUY/@@download/ENCFF100EUY.bed.gz
curl -o example_data/ChIP/ENCFF814OVW.bed.gz -L https://www.encodeproject.org/files/ENCFF814OVW/@@download/ENCFF814OVW.bed.gz
curl -o example_data/ChIP/ENCFF199XFV.bed.gz -L https://www.encodeproject.org/files/ENCFF199XFV/@@download/ENCFF199XFV.bed.gz
curl -o example_data/ChIP/ENCFF195BCQ.bed.gz -L https://www.encodeproject.org/files/ENCFF195BCQ/@@download/ENCFF195BCQ.bed.gz
curl -o example_data/ChIP/ENCFF820GXU.bed.gz -L https://www.encodeproject.org/files/ENCFF820GXU/@@download/ENCFF820GXU.bed.gz
curl -o example_data/ChIP/ENCFF532BBC.bed.gz -L https://www.encodeproject.org/files/ENCFF532BBC/@@download/ENCFF532BBC.bed.gz
curl -o example_data/ChIP/ENCFF600UCD.bed.gz -L https://www.encodeproject.org/files/ENCFF600UCD/@@download/ENCFF600UCD.bed.gz
curl -o example_data/ChIP/ENCFF580OBO.bed.gz -L https://www.encodeproject.org/files/ENCFF580OBO/@@download/ENCFF580OBO.bed.gz
curl -o example_data/ChIP/ENCFF523DZS.bed.gz -L https://www.encodeproject.org/files/ENCFF523DZS/@@download/ENCFF523DZS.bed.gz
curl -o example_data/ChIP/ENCFF760SXR.bed.gz -L https://www.encodeproject.org/files/ENCFF760SXR/@@download/ENCFF760SXR.bed.gz
curl -o example_data/ChIP/ENCFF501NEC.bed.gz -L https://www.encodeproject.org/files/ENCFF501NEC/@@download/ENCFF501NEC.bed.gz
curl -o example_data/ChIP/ENCFF924RRD.bed.gz -L https://www.encodeproject.org/files/ENCFF924RRD/@@download/ENCFF924RRD.bed.gz
curl -o example_data/ChIP/ENCFF256SLO.bed.gz -L https://www.encodeproject.org/files/ENCFF256SLO/@@download/ENCFF256SLO.bed.gz
curl -o example_data/ChIP/ENCFF905ZFF.bed.gz -L https://www.encodeproject.org/files/ENCFF905ZFF/@@download/ENCFF905ZFF.bed.gz
curl -o example_data/ChIP/ENCFF574VKT.bed.gz -L https://www.encodeproject.org/files/ENCFF574VKT/@@download/ENCFF574VKT.bed.gz
curl -o example_data/ChIP/ENCFF249OVZ.bed.gz -L https://www.encodeproject.org/files/ENCFF249OVZ/@@download/ENCFF249OVZ.bed.gz
curl -o example_data/ChIP/ENCFF432EKX.bed.gz -L https://www.encodeproject.org/files/ENCFF432EKX/@@download/ENCFF432EKX.bed.gz
curl -o example_data/ChIP/ENCFF474FPM.bed.gz -L https://www.encodeproject.org/files/ENCFF474FPM/@@download/ENCFF474FPM.bed.gz
curl -o example_data/ChIP/ENCFF038DLA.bed.gz -L https://www.encodeproject.org/files/ENCFF038DLA/@@download/ENCFF038DLA.bed.gz
curl -o example_data/ChIP/ENCFF318MOC.bed.gz -L https://www.encodeproject.org/files/ENCFF318MOC/@@download/ENCFF318MOC.bed.gz
curl -o example_data/ChIP/ENCFF351KHY.bed.gz -L https://www.encodeproject.org/files/ENCFF351KHY/@@download/ENCFF351KHY.bed.gz
curl -o example_data/ChIP/ENCFF104SSP.bed.gz -L https://www.encodeproject.org/files/ENCFF104SSP/@@download/ENCFF104SSP.bed.gz
curl -o example_data/ChIP/ENCFF731VFB.bed.gz -L https://www.encodeproject.org/files/ENCFF731VFB/@@download/ENCFF731VFB.bed.gz
curl -o example_data/ChIP/ENCFF619NUF.bed.gz -L https://www.encodeproject.org/files/ENCFF619NUF/@@download/ENCFF619NUF.bed.gz
curl -o example_data/ChIP/ENCFF548MOC.bed.gz -L https://www.encodeproject.org/files/ENCFF548MOC/@@download/ENCFF548MOC.bed.gz
curl -o example_data/ChIP/ENCFF740TXB.bed.gz -L https://www.encodeproject.org/files/ENCFF740TXB/@@download/ENCFF740TXB.bed.gz
curl -o example_data/ChIP/ENCFF816LUA.bed.gz -L https://www.encodeproject.org/files/ENCFF816LUA/@@download/ENCFF816LUA.bed.gz
curl -o example_data/ChIP/ENCFF732FWJ.bed.gz -L https://www.encodeproject.org/files/ENCFF732FWJ/@@download/ENCFF732FWJ.bed.gz
curl -o example_data/ChIP/ENCFF865ORH.bed.gz -L https://www.encodeproject.org/files/ENCFF865ORH/@@download/ENCFF865ORH.bed.gz
curl -o example_data/ChIP/ENCFF502SLH.bed.gz -L https://www.encodeproject.org/files/ENCFF502SLH/@@download/ENCFF502SLH.bed.gz
curl -o example_data/ChIP/ENCFF992OGZ.bed.gz -L https://www.encodeproject.org/files/ENCFF992OGZ/@@download/ENCFF992OGZ.bed.gz
curl -o example_data/ChIP/ENCFF239YHI.bed.gz -L https://www.encodeproject.org/files/ENCFF239YHI/@@download/ENCFF239YHI.bed.gz
curl -o example_data/ChIP/ENCFF965DLY.bed.gz -L https://www.encodeproject.org/files/ENCFF965DLY/@@download/ENCFF965DLY.bed.gz
curl -o example_data/ChIP/ENCFF893EGY.bed.gz -L https://www.encodeproject.org/files/ENCFF893EGY/@@download/ENCFF893EGY.bed.gz
curl -o example_data/ChIP/ENCFF731KRI.bed.gz -L https://www.encodeproject.org/files/ENCFF731KRI/@@download/ENCFF731KRI.bed.gz
curl -o example_data/ChIP/ENCFF343LZT.bed.gz -L https://www.encodeproject.org/files/ENCFF343LZT/@@download/ENCFF343LZT.bed.gz
curl -o example_data/ChIP/ENCFF736BHD.bed.gz -L https://www.encodeproject.org/files/ENCFF736BHD/@@download/ENCFF736BHD.bed.gz
curl -o example_data/ChIP/ENCFF669XOU.bed.gz -L https://www.encodeproject.org/files/ENCFF669XOU/@@download/ENCFF669XOU.bed.gz
curl -o example_data/ChIP/ENCFF765SPJ.bed.gz -L https://www.encodeproject.org/files/ENCFF765SPJ/@@download/ENCFF765SPJ.bed.gz
curl -o example_data/ChIP/ENCFF069WPC.bed.gz -L https://www.encodeproject.org/files/ENCFF069WPC/@@download/ENCFF069WPC.bed.gz
curl -o example_data/ChIP/ENCFF087NOZ.bed.gz -L https://www.encodeproject.org/files/ENCFF087NOZ/@@download/ENCFF087NOZ.bed.gz
curl -o example_data/ChIP/ENCFF539ATG.bed.gz -L https://www.encodeproject.org/files/ENCFF539ATG/@@download/ENCFF539ATG.bed.gz
curl -o example_data/ChIP/ENCFF318IJE.bed.gz -L https://www.encodeproject.org/files/ENCFF318IJE/@@download/ENCFF318IJE.bed.gz
curl -o example_data/ChIP/ENCFF621ZFI.bed.gz -L https://www.encodeproject.org/files/ENCFF621ZFI/@@download/ENCFF621ZFI.bed.gz
curl -o example_data/ChIP/ENCFF787NDL.bed.gz -L https://www.encodeproject.org/files/ENCFF787NDL/@@download/ENCFF787NDL.bed.gz
curl -o example_data/ChIP/ENCFF688MZB.bed.gz -L https://www.encodeproject.org/files/ENCFF688MZB/@@download/ENCFF688MZB.bed.gz
curl -o example_data/ChIP/ENCFF013EPO.bed.gz -L https://www.encodeproject.org/files/ENCFF013EPO/@@download/ENCFF013EPO.bed.gz
curl -o example_data/ChIP/ENCFF433TRM.bed.gz -L https://www.encodeproject.org/files/ENCFF433TRM/@@download/ENCFF433TRM.bed.gz
curl -o example_data/ChIP/ENCFF910STC.bed.gz -L https://www.encodeproject.org/files/ENCFF910STC/@@download/ENCFF910STC.bed.gz
curl -o example_data/ChIP/ENCFF588FVZ.bed.gz -L https://www.encodeproject.org/files/ENCFF588FVZ/@@download/ENCFF588FVZ.bed.gz
curl -o example_data/ChIP/ENCFF107DOK.bed.gz -L https://www.encodeproject.org/files/ENCFF107DOK/@@download/ENCFF107DOK.bed.gz
curl -o example_data/ChIP/ENCFF280NHA.bed.gz -L https://www.encodeproject.org/files/ENCFF280NHA/@@download/ENCFF280NHA.bed.gz
curl -o example_data/ChIP/ENCFF020VAN.bed.gz -L https://www.encodeproject.org/files/ENCFF020VAN/@@download/ENCFF020VAN.bed.gz
curl -o example_data/ChIP/ENCFF704WGH.bed.gz -L https://www.encodeproject.org/files/ENCFF704WGH/@@download/ENCFF704WGH.bed.gz
curl -o example_data/ChIP/ENCFF471JEZ.bed.gz -L https://www.encodeproject.org/files/ENCFF471JEZ/@@download/ENCFF471JEZ.bed.gz
curl -o example_data/ChIP/ENCFF381LPZ.bed.gz -L https://www.encodeproject.org/files/ENCFF381LPZ/@@download/ENCFF381LPZ.bed.gz
curl -o example_data/ChIP/ENCFF895AVT.bed.gz -L https://www.encodeproject.org/files/ENCFF895AVT/@@download/ENCFF895AVT.bed.gz
curl -o example_data/ChIP/ENCFF248QFM.bed.gz -L https://www.encodeproject.org/files/ENCFF248QFM/@@download/ENCFF248QFM.bed.gz
curl -o example_data/ChIP/ENCFF710XKN.bed.gz -L https://www.encodeproject.org/files/ENCFF710XKN/@@download/ENCFF710XKN.bed.gz
curl -o example_data/ChIP/ENCFF630PTF.bed.gz -L https://www.encodeproject.org/files/ENCFF630PTF/@@download/ENCFF630PTF.bed.gz
curl -o example_data/ChIP/ENCFF983LSZ.bed.gz -L https://www.encodeproject.org/files/ENCFF983LSZ/@@download/ENCFF983LSZ.bed.gz
curl -o example_data/ChIP/ENCFF630IOW.bed.gz -L https://www.encodeproject.org/files/ENCFF630IOW/@@download/ENCFF630IOW.bed.gz
curl -o example_data/ChIP/ENCFF770JYR.bed.gz -L https://www.encodeproject.org/files/ENCFF770JYR/@@download/ENCFF770JYR.bed.gz
curl -o example_data/ChIP/ENCFF502GLZ.bed.gz -L https://www.encodeproject.org/files/ENCFF502GLZ/@@download/ENCFF502GLZ.bed.gz
curl -o example_data/ChIP/ENCFF066ODW.bed.gz -L https://www.encodeproject.org/files/ENCFF066ODW/@@download/ENCFF066ODW.bed.gz
curl -o example_data/ChIP/ENCFF554HWG.bed.gz -L https://www.encodeproject.org/files/ENCFF554HWG/@@download/ENCFF554HWG.bed.gz
curl -o example_data/ChIP/ENCFF893XMO.bed.gz -L https://www.encodeproject.org/files/ENCFF893XMO/@@download/ENCFF893XMO.bed.gz
curl -o example_data/ChIP/ENCFF303AHH.bed.gz -L https://www.encodeproject.org/files/ENCFF303AHH/@@download/ENCFF303AHH.bed.gz
curl -o example_data/ChIP/ENCFF158SZN.bed.gz -L https://www.encodeproject.org/files/ENCFF158SZN/@@download/ENCFF158SZN.bed.gz
curl -o example_data/ChIP/ENCFF980PCO.bed.gz -L https://www.encodeproject.org/files/ENCFF980PCO/@@download/ENCFF980PCO.bed.gz
curl -o example_data/ChIP/ENCFF679JMM.bed.gz -L https://www.encodeproject.org/files/ENCFF679JMM/@@download/ENCFF679JMM.bed.gz
curl -o example_data/ChIP/ENCFF357EFX.bed.gz -L https://www.encodeproject.org/files/ENCFF357EFX/@@download/ENCFF357EFX.bed.gz
curl -o example_data/ChIP/ENCFF108BXU.bed.gz -L https://www.encodeproject.org/files/ENCFF108BXU/@@download/ENCFF108BXU.bed.gz
curl -o example_data/ChIP/ENCFF801XUK.bed.gz -L https://www.encodeproject.org/files/ENCFF801XUK/@@download/ENCFF801XUK.bed.gz
curl -o example_data/ChIP/ENCFF186LXG.bed.gz -L https://www.encodeproject.org/files/ENCFF186LXG/@@download/ENCFF186LXG.bed.gz
curl -o example_data/ChIP/ENCFF986EKN.bed.gz -L https://www.encodeproject.org/files/ENCFF986EKN/@@download/ENCFF986EKN.bed.gz
curl -o example_data/ChIP/ENCFF729YEP.bed.gz -L https://www.encodeproject.org/files/ENCFF729YEP/@@download/ENCFF729YEP.bed.gz
curl -o example_data/ChIP/ENCFF707GZA.bed.gz -L https://www.encodeproject.org/files/ENCFF707GZA/@@download/ENCFF707GZA.bed.gz
curl -o example_data/ChIP/ENCFF284RTS.bed.gz -L https://www.encodeproject.org/files/ENCFF284RTS/@@download/ENCFF284RTS.bed.gz
curl -o example_data/ChIP/ENCFF761HCV.bed.gz -L https://www.encodeproject.org/files/ENCFF761HCV/@@download/ENCFF761HCV.bed.gz
curl -o example_data/ChIP/ENCFF127BGA.bed.gz -L https://www.encodeproject.org/files/ENCFF127BGA/@@download/ENCFF127BGA.bed.gz
curl -o example_data/ChIP/ENCFF558RLK.bed.gz -L https://www.encodeproject.org/files/ENCFF558RLK/@@download/ENCFF558RLK.bed.gz
curl -o example_data/ChIP/ENCFF794CQT.bed.gz -L https://www.encodeproject.org/files/ENCFF794CQT/@@download/ENCFF794CQT.bed.gz
curl -o example_data/ChIP/ENCFF571GHQ.bed.gz -L https://www.encodeproject.org/files/ENCFF571GHQ/@@download/ENCFF571GHQ.bed.gz
curl -o example_data/ChIP/ENCFF061FXA.bed.gz -L https://www.encodeproject.org/files/ENCFF061FXA/@@download/ENCFF061FXA.bed.gz
curl -o example_data/ChIP/ENCFF173DOO.bed.gz -L https://www.encodeproject.org/files/ENCFF173DOO/@@download/ENCFF173DOO.bed.gz
curl -o example_data/ChIP/ENCFF006VQI.bed.gz -L https://www.encodeproject.org/files/ENCFF006VQI/@@download/ENCFF006VQI.bed.gz
curl -o example_data/ChIP/ENCFF627TDV.bed.gz -L https://www.encodeproject.org/files/ENCFF627TDV/@@download/ENCFF627TDV.bed.gz
curl -o example_data/ChIP/ENCFF864MKA.bed.gz -L https://www.encodeproject.org/files/ENCFF864MKA/@@download/ENCFF864MKA.bed.gz
curl -o example_data/ChIP/ENCFF372EFU.bed.gz -L https://www.encodeproject.org/files/ENCFF372EFU/@@download/ENCFF372EFU.bed.gz
curl -o example_data/ChIP/ENCFF709GMR.bed.gz -L https://www.encodeproject.org/files/ENCFF709GMR/@@download/ENCFF709GMR.bed.gz
curl -o example_data/ChIP/ENCFF169ZEG.bed.gz -L https://www.encodeproject.org/files/ENCFF169ZEG/@@download/ENCFF169ZEG.bed.gz
curl -o example_data/ChIP/ENCFF390CIX.bed.gz -L https://www.encodeproject.org/files/ENCFF390CIX/@@download/ENCFF390CIX.bed.gz
curl -o example_data/ChIP/ENCFF565HZT.bed.gz -L https://www.encodeproject.org/files/ENCFF565HZT/@@download/ENCFF565HZT.bed.gz
curl -o example_data/ChIP/ENCFF816GGH.bed.gz -L https://www.encodeproject.org/files/ENCFF816GGH/@@download/ENCFF816GGH.bed.gz
curl -o example_data/ChIP/ENCFF342BWT.bed.gz -L https://www.encodeproject.org/files/ENCFF342BWT/@@download/ENCFF342BWT.bed.gz
curl -o example_data/ChIP/ENCFF999VZP.bed.gz -L https://www.encodeproject.org/files/ENCFF999VZP/@@download/ENCFF999VZP.bed.gz
curl -o example_data/ChIP/ENCFF074INK.bed.gz -L https://www.encodeproject.org/files/ENCFF074INK/@@download/ENCFF074INK.bed.gz
curl -o example_data/ChIP/ENCFF174FXW.bed.gz -L https://www.encodeproject.org/files/ENCFF174FXW/@@download/ENCFF174FXW.bed.gz
curl -o example_data/ChIP/ENCFF390FAE.bed.gz -L https://www.encodeproject.org/files/ENCFF390FAE/@@download/ENCFF390FAE.bed.gz
curl -o example_data/ChIP/ENCFF440RYZ.bed.gz -L https://www.encodeproject.org/files/ENCFF440RYZ/@@download/ENCFF440RYZ.bed.gz
curl -o example_data/ChIP/ENCFF495XXK.bed.gz -L https://www.encodeproject.org/files/ENCFF495XXK/@@download/ENCFF495XXK.bed.gz
curl -o example_data/ChIP/ENCFF388SSE.bed.gz -L https://www.encodeproject.org/files/ENCFF388SSE/@@download/ENCFF388SSE.bed.gz
curl -o example_data/ChIP/ENCFF425IEU.bed.gz -L https://www.encodeproject.org/files/ENCFF425IEU/@@download/ENCFF425IEU.bed.gz
curl -o example_data/ChIP/ENCFF842LET.bed.gz -L https://www.encodeproject.org/files/ENCFF842LET/@@download/ENCFF842LET.bed.gz
curl -o example_data/ChIP/ENCFF847DMA.bed.gz -L https://www.encodeproject.org/files/ENCFF847DMA/@@download/ENCFF847DMA.bed.gz
curl -o example_data/ChIP/ENCFF597SEX.bed.gz -L https://www.encodeproject.org/files/ENCFF597SEX/@@download/ENCFF597SEX.bed.gz
curl -o example_data/ChIP/ENCFF408JZT.bed.gz -L https://www.encodeproject.org/files/ENCFF408JZT/@@download/ENCFF408JZT.bed.gz
curl -o example_data/ChIP/ENCFF499XZJ.bed.gz -L https://www.encodeproject.org/files/ENCFF499XZJ/@@download/ENCFF499XZJ.bed.gz
curl -o example_data/ChIP/ENCFF048JXD.bed.gz -L https://www.encodeproject.org/files/ENCFF048JXD/@@download/ENCFF048JXD.bed.gz
curl -o example_data/ChIP/ENCFF703AHS.bed.gz -L https://www.encodeproject.org/files/ENCFF703AHS/@@download/ENCFF703AHS.bed.gz
curl -o example_data/ChIP/ENCFF163GOO.bed.gz -L https://www.encodeproject.org/files/ENCFF163GOO/@@download/ENCFF163GOO.bed.gz
curl -o example_data/ChIP/ENCFF308OHV.bed.gz -L https://www.encodeproject.org/files/ENCFF308OHV/@@download/ENCFF308OHV.bed.gz
curl -o example_data/ChIP/ENCFF239GUJ.bed.gz -L https://www.encodeproject.org/files/ENCFF239GUJ/@@download/ENCFF239GUJ.bed.gz
curl -o example_data/ChIP/ENCFF598JXU.bed.gz -L https://www.encodeproject.org/files/ENCFF598JXU/@@download/ENCFF598JXU.bed.gz
curl -o example_data/ChIP/ENCFF613KAV.bed.gz -L https://www.encodeproject.org/files/ENCFF613KAV/@@download/ENCFF613KAV.bed.gz
curl -o example_data/ChIP/ENCFF537FQU.bed.gz -L https://www.encodeproject.org/files/ENCFF537FQU/@@download/ENCFF537FQU.bed.gz
curl -o example_data/ChIP/ENCFF821OGZ.bed.gz -L https://www.encodeproject.org/files/ENCFF821OGZ/@@download/ENCFF821OGZ.bed.gz
curl -o example_data/ChIP/ENCFF328PCV.bed.gz -L https://www.encodeproject.org/files/ENCFF328PCV/@@download/ENCFF328PCV.bed.gz
curl -o example_data/ChIP/ENCFF026PTJ.bed.gz -L https://www.encodeproject.org/files/ENCFF026PTJ/@@download/ENCFF026PTJ.bed.gz
curl -o example_data/ChIP/ENCFF160SDR.bed.gz -L https://www.encodeproject.org/files/ENCFF160SDR/@@download/ENCFF160SDR.bed.gz
curl -o example_data/ChIP/ENCFF127ZEN.bed.gz -L https://www.encodeproject.org/files/ENCFF127ZEN/@@download/ENCFF127ZEN.bed.gz
curl -o example_data/ChIP/ENCFF029NQZ.bed.gz -L https://www.encodeproject.org/files/ENCFF029NQZ/@@download/ENCFF029NQZ.bed.gz
curl -o example_data/ChIP/ENCFF967MPB.bed.gz -L https://www.encodeproject.org/files/ENCFF967MPB/@@download/ENCFF967MPB.bed.gz
curl -o example_data/ChIP/ENCFF308ZER.bed.gz -L https://www.encodeproject.org/files/ENCFF308ZER/@@download/ENCFF308ZER.bed.gz
curl -o example_data/ChIP/ENCFF522ZND.bed.gz -L https://www.encodeproject.org/files/ENCFF522ZND/@@download/ENCFF522ZND.bed.gz
curl -o example_data/ChIP/ENCFF767KNY.bed.gz -L https://www.encodeproject.org/files/ENCFF767KNY/@@download/ENCFF767KNY.bed.gz
curl -o example_data/ChIP/ENCFF904JNR.bed.gz -L https://www.encodeproject.org/files/ENCFF904JNR/@@download/ENCFF904JNR.bed.gz
curl -o example_data/ChIP/ENCFF932RYJ.bed.gz -L https://www.encodeproject.org/files/ENCFF932RYJ/@@download/ENCFF932RYJ.bed.gz
curl -o example_data/ChIP/ENCFF377VXM.bed.gz -L https://www.encodeproject.org/files/ENCFF377VXM/@@download/ENCFF377VXM.bed.gz
curl -o example_data/ChIP/ENCFF289GYP.bed.gz -L https://www.encodeproject.org/files/ENCFF289GYP/@@download/ENCFF289GYP.bed.gz
curl -o example_data/ChIP/ENCFF419DVZ.bed.gz -L https://www.encodeproject.org/files/ENCFF419DVZ/@@download/ENCFF419DVZ.bed.gz
curl -o example_data/ChIP/ENCFF202YXL.bed.gz -L https://www.encodeproject.org/files/ENCFF202YXL/@@download/ENCFF202YXL.bed.gz
curl -o example_data/ChIP/ENCFF367FBJ.bed.gz -L https://www.encodeproject.org/files/ENCFF367FBJ/@@download/ENCFF367FBJ.bed.gz
curl -o example_data/ChIP/ENCFF876TYA.bed.gz -L https://www.encodeproject.org/files/ENCFF876TYA/@@download/ENCFF876TYA.bed.gz
curl -o example_data/ChIP/ENCFF708VEF.bed.gz -L https://www.encodeproject.org/files/ENCFF708VEF/@@download/ENCFF708VEF.bed.gz
curl -o example_data/ChIP/ENCFF325GHA.bed.gz -L https://www.encodeproject.org/files/ENCFF325GHA/@@download/ENCFF325GHA.bed.gz
curl -o example_data/ChIP/ENCFF561CUI.bed.gz -L https://www.encodeproject.org/files/ENCFF561CUI/@@download/ENCFF561CUI.bed.gz
curl -o example_data/ChIP/ENCFF919JDR.bed.gz -L https://www.encodeproject.org/files/ENCFF919JDR/@@download/ENCFF919JDR.bed.gz
curl -o example_data/ChIP/ENCFF096ZZY.bed.gz -L https://www.encodeproject.org/files/ENCFF096ZZY/@@download/ENCFF096ZZY.bed.gz
curl -o example_data/ChIP/ENCFF250TYL.bed.gz -L https://www.encodeproject.org/files/ENCFF250TYL/@@download/ENCFF250TYL.bed.gz
curl -o example_data/ChIP/ENCFF067SPH.bed.gz -L https://www.encodeproject.org/files/ENCFF067SPH/@@download/ENCFF067SPH.bed.gz
curl -o example_data/ChIP/ENCFF730PDT.bed.gz -L https://www.encodeproject.org/files/ENCFF730PDT/@@download/ENCFF730PDT.bed.gz
curl -o example_data/ChIP/ENCFF441AFD.bed.gz -L https://www.encodeproject.org/files/ENCFF441AFD/@@download/ENCFF441AFD.bed.gz
curl -o example_data/ChIP/ENCFF192QZI.bed.gz -L https://www.encodeproject.org/files/ENCFF192QZI/@@download/ENCFF192QZI.bed.gz
curl -o example_data/ChIP/ENCFF638ANP.bed.gz -L https://www.encodeproject.org/files/ENCFF638ANP/@@download/ENCFF638ANP.bed.gz
curl -o example_data/ChIP/ENCFF149KLC.bed.gz -L https://www.encodeproject.org/files/ENCFF149KLC/@@download/ENCFF149KLC.bed.gz
curl -o example_data/ChIP/ENCFF123ODE.bed.gz -L https://www.encodeproject.org/files/ENCFF123ODE/@@download/ENCFF123ODE.bed.gz
curl -o example_data/ChIP/ENCFF545KPK.bed.gz -L https://www.encodeproject.org/files/ENCFF545KPK/@@download/ENCFF545KPK.bed.gz
curl -o example_data/ChIP/ENCFF143CSV.bed.gz -L https://www.encodeproject.org/files/ENCFF143CSV/@@download/ENCFF143CSV.bed.gz
curl -o example_data/ChIP/ENCFF221SOC.bed.gz -L https://www.encodeproject.org/files/ENCFF221SOC/@@download/ENCFF221SOC.bed.gz
curl -o example_data/ChIP/ENCFF101TBI.bed.gz -L https://www.encodeproject.org/files/ENCFF101TBI/@@download/ENCFF101TBI.bed.gz
curl -o example_data/ChIP/ENCFF442EIL.bed.gz -L https://www.encodeproject.org/files/ENCFF442EIL/@@download/ENCFF442EIL.bed.gz
curl -o example_data/ChIP/ENCFF409EHG.bed.gz -L https://www.encodeproject.org/files/ENCFF409EHG/@@download/ENCFF409EHG.bed.gz
curl -o example_data/ChIP/ENCFF500YBF.bed.gz -L https://www.encodeproject.org/files/ENCFF500YBF/@@download/ENCFF500YBF.bed.gz
curl -o example_data/ChIP/ENCFF240CXQ.bed.gz -L https://www.encodeproject.org/files/ENCFF240CXQ/@@download/ENCFF240CXQ.bed.gz
curl -o example_data/ChIP/ENCFF571STC.bed.gz -L https://www.encodeproject.org/files/ENCFF571STC/@@download/ENCFF571STC.bed.gz
curl -o example_data/ChIP/ENCFF915KPO.bed.gz -L https://www.encodeproject.org/files/ENCFF915KPO/@@download/ENCFF915KPO.bed.gz
curl -o example_data/ChIP/ENCFF383MZV.bed.gz -L https://www.encodeproject.org/files/ENCFF383MZV/@@download/ENCFF383MZV.bed.gz
curl -o example_data/ChIP/ENCFF216VTQ.bed.gz -L https://www.encodeproject.org/files/ENCFF216VTQ/@@download/ENCFF216VTQ.bed.gz
curl -o example_data/ChIP/ENCFF392BMO.bed.gz -L https://www.encodeproject.org/files/ENCFF392BMO/@@download/ENCFF392BMO.bed.gz
curl -o example_data/ChIP/ENCFF561KEC.bed.gz -L https://www.encodeproject.org/files/ENCFF561KEC/@@download/ENCFF561KEC.bed.gz
curl -o example_data/ChIP/ENCFF886CYZ.bed.gz -L https://www.encodeproject.org/files/ENCFF886CYZ/@@download/ENCFF886CYZ.bed.gz
curl -o example_data/ChIP/ENCFF649JTF.bed.gz -L https://www.encodeproject.org/files/ENCFF649JTF/@@download/ENCFF649JTF.bed.gz
curl -o example_data/ChIP/ENCFF201DIS.bed.gz -L https://www.encodeproject.org/files/ENCFF201DIS/@@download/ENCFF201DIS.bed.gz
curl -o example_data/ChIP/ENCFF962CNO.bed.gz -L https://www.encodeproject.org/files/ENCFF962CNO/@@download/ENCFF962CNO.bed.gz
curl -o example_data/ChIP/ENCFF007ZEZ.bed.gz -L https://www.encodeproject.org/files/ENCFF007ZEZ/@@download/ENCFF007ZEZ.bed.gz
curl -o example_data/ChIP/ENCFF629XNY.bed.gz -L https://www.encodeproject.org/files/ENCFF629XNY/@@download/ENCFF629XNY.bed.gz
curl -o example_data/ChIP/ENCFF030PPG.bed.gz -L https://www.encodeproject.org/files/ENCFF030PPG/@@download/ENCFF030PPG.bed.gz
curl -o example_data/ChIP/ENCFF634YIZ.bed.gz -L https://www.encodeproject.org/files/ENCFF634YIZ/@@download/ENCFF634YIZ.bed.gz
curl -o example_data/ChIP/ENCFF741JPG.bed.gz -L https://www.encodeproject.org/files/ENCFF741JPG/@@download/ENCFF741JPG.bed.gz
curl -o example_data/ChIP/ENCFF554AFK.bed.gz -L https://www.encodeproject.org/files/ENCFF554AFK/@@download/ENCFF554AFK.bed.gz
curl -o example_data/ChIP/ENCFF725XMW.bed.gz -L https://www.encodeproject.org/files/ENCFF725XMW/@@download/ENCFF725XMW.bed.gz
curl -o example_data/ChIP/ENCFF531YVL.bed.gz -L https://www.encodeproject.org/files/ENCFF531YVL/@@download/ENCFF531YVL.bed.gz
curl -o example_data/ChIP/ENCFF023KLC.bed.gz -L https://www.encodeproject.org/files/ENCFF023KLC/@@download/ENCFF023KLC.bed.gz
curl -o example_data/ChIP/ENCFF977XMW.bed.gz -L https://www.encodeproject.org/files/ENCFF977XMW/@@download/ENCFF977XMW.bed.gz
curl -o example_data/ChIP/ENCFF679URO.bed.gz -L https://www.encodeproject.org/files/ENCFF679URO/@@download/ENCFF679URO.bed.gz
curl -o example_data/ChIP/ENCFF071SFB.bed.gz -L https://www.encodeproject.org/files/ENCFF071SFB/@@download/ENCFF071SFB.bed.gz
curl -o example_data/ChIP/ENCFF659WDZ.bed.gz -L https://www.encodeproject.org/files/ENCFF659WDZ/@@download/ENCFF659WDZ.bed.gz
curl -o example_data/ChIP/ENCFF138QKI.bed.gz -L https://www.encodeproject.org/files/ENCFF138QKI/@@download/ENCFF138QKI.bed.gz
curl -o example_data/ChIP/ENCFF322AHC.bed.gz -L https://www.encodeproject.org/files/ENCFF322AHC/@@download/ENCFF322AHC.bed.gz
curl -o example_data/ChIP/ENCFF115KVP.bed.gz -L https://www.encodeproject.org/files/ENCFF115KVP/@@download/ENCFF115KVP.bed.gz
curl -o example_data/ChIP/ENCFF698AVD.bed.gz -L https://www.encodeproject.org/files/ENCFF698AVD/@@download/ENCFF698AVD.bed.gz
curl -o example_data/ChIP/ENCFF598JQB.bed.gz -L https://www.encodeproject.org/files/ENCFF598JQB/@@download/ENCFF598JQB.bed.gz
curl -o example_data/ChIP/ENCFF041EDI.bed.gz -L https://www.encodeproject.org/files/ENCFF041EDI/@@download/ENCFF041EDI.bed.gz
curl -o example_data/ChIP/ENCFF834CPL.bed.gz -L https://www.encodeproject.org/files/ENCFF834CPL/@@download/ENCFF834CPL.bed.gz
curl -o example_data/ChIP/ENCFF650YEL.bed.gz -L https://www.encodeproject.org/files/ENCFF650YEL/@@download/ENCFF650YEL.bed.gz
curl -o example_data/ChIP/ENCFF849LEC.bed.gz -L https://www.encodeproject.org/files/ENCFF849LEC/@@download/ENCFF849LEC.bed.gz
curl -o example_data/ChIP/ENCFF892MVJ.bed.gz -L https://www.encodeproject.org/files/ENCFF892MVJ/@@download/ENCFF892MVJ.bed.gz
curl -o example_data/ChIP/ENCFF710HFR.bed.gz -L https://www.encodeproject.org/files/ENCFF710HFR/@@download/ENCFF710HFR.bed.gz
curl -o example_data/ChIP/ENCFF682ROE.bed.gz -L https://www.encodeproject.org/files/ENCFF682ROE/@@download/ENCFF682ROE.bed.gz
curl -o example_data/ChIP/ENCFF310MNI.bed.gz -L https://www.encodeproject.org/files/ENCFF310MNI/@@download/ENCFF310MNI.bed.gz
curl -o example_data/ChIP/ENCFF648COE.bed.gz -L https://www.encodeproject.org/files/ENCFF648COE/@@download/ENCFF648COE.bed.gz
curl -o example_data/ChIP/ENCFF303PVS.bed.gz -L https://www.encodeproject.org/files/ENCFF303PVS/@@download/ENCFF303PVS.bed.gz
curl -o example_data/ChIP/ENCFF586YBO.bed.gz -L https://www.encodeproject.org/files/ENCFF586YBO/@@download/ENCFF586YBO.bed.gz
curl -o example_data/ChIP/ENCFF739TEK.bed.gz -L https://www.encodeproject.org/files/ENCFF739TEK/@@download/ENCFF739TEK.bed.gz
curl -o example_data/ChIP/ENCFF038FQN.bed.gz -L https://www.encodeproject.org/files/ENCFF038FQN/@@download/ENCFF038FQN.bed.gz
curl -o example_data/ChIP/ENCFF051GFC.bed.gz -L https://www.encodeproject.org/files/ENCFF051GFC/@@download/ENCFF051GFC.bed.gz
curl -o example_data/ChIP/ENCFF510FWE.bed.gz -L https://www.encodeproject.org/files/ENCFF510FWE/@@download/ENCFF510FWE.bed.gz
curl -o example_data/ChIP/ENCFF294EYG.bed.gz -L https://www.encodeproject.org/files/ENCFF294EYG/@@download/ENCFF294EYG.bed.gz
curl -o example_data/ChIP/ENCFF097FNP.bed.gz -L https://www.encodeproject.org/files/ENCFF097FNP/@@download/ENCFF097FNP.bed.gz
curl -o example_data/ChIP/ENCFF048MUD.bed.gz -L https://www.encodeproject.org/files/ENCFF048MUD/@@download/ENCFF048MUD.bed.gz
curl -o example_data/ChIP/ENCFF993AQH.bed.gz -L https://www.encodeproject.org/files/ENCFF993AQH/@@download/ENCFF993AQH.bed.gz
curl -o example_data/ChIP/ENCFF796WOX.bed.gz -L https://www.encodeproject.org/files/ENCFF796WOX/@@download/ENCFF796WOX.bed.gz
curl -o example_data/ChIP/ENCFF897SXY.bed.gz -L https://www.encodeproject.org/files/ENCFF897SXY/@@download/ENCFF897SXY.bed.gz
curl -o example_data/ChIP/ENCFF356UHL.bed.gz -L https://www.encodeproject.org/files/ENCFF356UHL/@@download/ENCFF356UHL.bed.gz
curl -o example_data/ChIP/ENCFF434KNT.bed.gz -L https://www.encodeproject.org/files/ENCFF434KNT/@@download/ENCFF434KNT.bed.gz
curl -o example_data/ChIP/ENCFF325UHA.bed.gz -L https://www.encodeproject.org/files/ENCFF325UHA/@@download/ENCFF325UHA.bed.gz
curl -o example_data/ChIP/ENCFF029EVO.bed.gz -L https://www.encodeproject.org/files/ENCFF029EVO/@@download/ENCFF029EVO.bed.gz
curl -o example_data/ChIP/ENCFF982SDT.bed.gz -L https://www.encodeproject.org/files/ENCFF982SDT/@@download/ENCFF982SDT.bed.gz
curl -o example_data/ChIP/ENCFF159JTG.bed.gz -L https://www.encodeproject.org/files/ENCFF159JTG/@@download/ENCFF159JTG.bed.gz
curl -o example_data/ChIP/ENCFF037ZFI.bed.gz -L https://www.encodeproject.org/files/ENCFF037ZFI/@@download/ENCFF037ZFI.bed.gz
curl -o example_data/ChIP/ENCFF398WRM.bed.gz -L https://www.encodeproject.org/files/ENCFF398WRM/@@download/ENCFF398WRM.bed.gz
curl -o example_data/ChIP/ENCFF857BTR.bed.gz -L https://www.encodeproject.org/files/ENCFF857BTR/@@download/ENCFF857BTR.bed.gz
curl -o example_data/ChIP/ENCFF566AND.bed.gz -L https://www.encodeproject.org/files/ENCFF566AND/@@download/ENCFF566AND.bed.gz
curl -o example_data/ChIP/ENCFF499JRS.bed.gz -L https://www.encodeproject.org/files/ENCFF499JRS/@@download/ENCFF499JRS.bed.gz
curl -o example_data/ChIP/ENCFF318OKO.bed.gz -L https://www.encodeproject.org/files/ENCFF318OKO/@@download/ENCFF318OKO.bed.gz
curl -o example_data/ChIP/ENCFF330EPK.bed.gz -L https://www.encodeproject.org/files/ENCFF330EPK/@@download/ENCFF330EPK.bed.gz
curl -o example_data/ChIP/ENCFF582WMX.bed.gz -L https://www.encodeproject.org/files/ENCFF582WMX/@@download/ENCFF582WMX.bed.gz
curl -o example_data/ChIP/ENCFF810IMH.bed.gz -L https://www.encodeproject.org/files/ENCFF810IMH/@@download/ENCFF810IMH.bed.gz
curl -o example_data/ChIP/ENCFF722ZQI.bed.gz -L https://www.encodeproject.org/files/ENCFF722ZQI/@@download/ENCFF722ZQI.bed.gz
curl -o example_data/ChIP/ENCFF096TGQ.bed.gz -L https://www.encodeproject.org/files/ENCFF096TGQ/@@download/ENCFF096TGQ.bed.gz
curl -o example_data/ChIP/ENCFF417RHJ.bed.gz -L https://www.encodeproject.org/files/ENCFF417RHJ/@@download/ENCFF417RHJ.bed.gz
curl -o example_data/ChIP/ENCFF894MXI.bed.gz -L https://www.encodeproject.org/files/ENCFF894MXI/@@download/ENCFF894MXI.bed.gz
curl -o example_data/ChIP/ENCFF724OZI.bed.gz -L https://www.encodeproject.org/files/ENCFF724OZI/@@download/ENCFF724OZI.bed.gz
curl -o example_data/ChIP/ENCFF513HGZ.bed.gz -L https://www.encodeproject.org/files/ENCFF513HGZ/@@download/ENCFF513HGZ.bed.gz
curl -o example_data/ChIP/ENCFF262VLK.bed.gz -L https://www.encodeproject.org/files/ENCFF262VLK/@@download/ENCFF262VLK.bed.gz
curl -o example_data/ChIP/ENCFF486NKJ.bed.gz -L https://www.encodeproject.org/files/ENCFF486NKJ/@@download/ENCFF486NKJ.bed.gz
curl -o example_data/ChIP/ENCFF151TGF.bed.gz -L https://www.encodeproject.org/files/ENCFF151TGF/@@download/ENCFF151TGF.bed.gz
curl -o example_data/ChIP/ENCFF231YVF.bed.gz -L https://www.encodeproject.org/files/ENCFF231YVF/@@download/ENCFF231YVF.bed.gz
curl -o example_data/ChIP/ENCFF134DFH.bed.gz -L https://www.encodeproject.org/files/ENCFF134DFH/@@download/ENCFF134DFH.bed.gz
curl -o example_data/ChIP/ENCFF191EVG.bed.gz -L https://www.encodeproject.org/files/ENCFF191EVG/@@download/ENCFF191EVG.bed.gz
curl -o example_data/ChIP/ENCFF370XEC.bed.gz -L https://www.encodeproject.org/files/ENCFF370XEC/@@download/ENCFF370XEC.bed.gz
curl -o example_data/ChIP/ENCFF478PLJ.bed.gz -L https://www.encodeproject.org/files/ENCFF478PLJ/@@download/ENCFF478PLJ.bed.gz
curl -o example_data/ChIP/ENCFF470TDZ.bed.gz -L https://www.encodeproject.org/files/ENCFF470TDZ/@@download/ENCFF470TDZ.bed.gz
curl -o example_data/ChIP/ENCFF675OTQ.bed.gz -L https://www.encodeproject.org/files/ENCFF675OTQ/@@download/ENCFF675OTQ.bed.gz
curl -o example_data/ChIP/ENCFF659JOX.bed.gz -L https://www.encodeproject.org/files/ENCFF659JOX/@@download/ENCFF659JOX.bed.gz
